server:
  port: 8888

spring:
  application:
    name: cloud-order-service
  #配置  zipkin + sleuth
  zipkin:
    base-url: http://zhenhongi.top:20001
  sleuth:
    sampler:
      probability: 1 #采样率值介于 0到 1之间  1 表示全采集
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true.
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
      defaultZone: http://localhost:7001/eureka
