server:
  port: 8006

spring:
  application:
    name: consul-provider-service
  cloud:
    consul:
      host: 47.92.23.23
#      host: localhost
      port: 22221
#      port: 8500
      discovery:
        service-name: ${spring.application.name}

