server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心开启路由功能
      routes:
        - id: payment_route             #配置路由id
#          uri: http://localhost:8001    #配置路由路径
          uri: lb://cloud-payment-service    #配置路由路径
          predicates:
            - Path=/payment/create/**
        - id: payment_route2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service    #配置路由路径   lb  LoadBalanced授予负载均衡能力
          predicates:
            - Path=/payment/discovery/** #Path  首字母大写
#            - After=2020-07-16T00:13:57.297+08:00[GMT+08:00]  #在这个时间段之后 开启
#            - Cookie=username,thz    #Cookie访问
#            - Header=X-Request-Id, \d+  #请求头要带有X-Request-Id属性且值为整数的正则表达式
          filters:
            - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头加上一对请求头 X-Request-Id = 1024

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      #表示是否将自己注册进EurekaServer默认为true.
      register-with-eureka: true
      #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
      fetch-registry: true
      defaultZone: http://localhost:7001/eureka
