server:
  port: 9000
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 47.92.23.23:8848

service-url:
  nacos-user-service: http://nacos-payment-provider