server:
  port: 9001
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 47.92.23.23:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'
